# Generated by Django 3.1.1 on 2020-10-05 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('city', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hotelName', models.CharField(default='Hotel', max_length=30)),
                ('location', models.CharField(default='', max_length=30)),
                ('people', models.IntegerField(default=None)),
                ('pricePerNight', models.FloatField(default=None)),
                ('averageRatings', models.FloatField(default=None)),
                ('stars', models.FloatField(default=None)),
                ('booked', models.BooleanField(default=False)),
                ('days', models.IntegerField()),
                ('whoBooked', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
    ]
