# Generated by Django 3.1.1 on 2020-10-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='days',
            field=models.IntegerField(blank=True),
        ),
    ]
