# Generated by Django 3.1.1 on 2020-10-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20201005_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='days',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
